import { Component } from "../API/Component";
import { IBelongAsset } from "../API/Interfaces/IBelongAsset";
import { IBelongCompany } from "../API/Interfaces/IBelongCompany";
import { IDeletable } from "../API/Interfaces/IDeletable";
import { IIdUlong } from "../API/Interfaces/IIdUlong";
import { JsonObject, JsonValue, uint, ulong } from "../API/Types";
import { BehaviourLogType } from "./BehaviourLogType";

/**
 * A debug message available to script writers to help debug and trace output from a BehaviourScript.
*/
export class BehaviourLog extends Component implements IIdUlong, IBelongCompany, IBelongAsset, IDeletable {
	/**
	 * Unique identifier of this log message.
	 */
	public id: ulong = NaN;
	/**
	 * The asset which whose behaviours created this log entry.
	 * {@link Asset.id}
	 */
	public asset: ulong = NaN;
	/**
	 * The company to which this log message belongs.
	 * {@link Company.id}
	 */
	public company: ulong = NaN;
	/**
	 * The behaviour to which this log message belongs.
	 * {@link Behaviour.id}
	 */
	public behaviour: ulong = NaN;
	/**
	 * The script which generated this log message.
	 * {@link BehaviourScript.id}
	 */
	public script: ulong = NaN;
	/**
	 * The category of message.
	 */
	public kind: BehaviourLogType;
	/**
	 * When the log entry was generated by the script.
	 */
	public dts: Date = DATE();
	/**
	 * The body of the message.
	 */
	public message: string = "";
	/**
	 * The line number of the script which generated this message.
	 */
	public line: uint = NaN;
	/**
	 * The character column where the error was generated.
	 */
	public character: uint = NaN;

	constructor(object: JsonObject) {
		super();
	}

	public override toJSON(): JsonValue {
		throw new Error("Method not implemented.");
	}
	public override fromJSON(input: JsonValue): void {
		throw new Error("Method not implemented.");
	}

	// IRequestable
	/**
	 * The <see cref="id"/> is the key.
	 */
public getKey(): string { return this.id.toString(); }

	/**
	 * Indicates whether this object was deleted.
	 */
	public deleted: boolean = false;
	/**
	 * Timestamp from the action that deleted or suspended this object.
	 */
	public since: Date = DATE();
}