import { Timezone } from './Timezone';

/**
 * A list of all supported system timezones.
 **/
export const TIMEZONES = [
	new Timezone("dateline-standard-time", "International Date Line West (UTC-12:00)", -720, false),
	new Timezone("utc-11", "Coordinated Universal Time-11 (UTC-11:00)", -660, false),
	new Timezone("aleutian-standard-time", "Aleutian Islands (UTC-10:00)", -600, true),
	new Timezone("hawaiian-standard-time", "Hawaii (UTC-10:00)", -600, false),
	new Timezone("marquesas-standard-time", "Marquesas Islands (UTC-09:30)", -570, false),
	new Timezone("alaskan-standard-time", "Alaska (UTC-09:00)", -540, true),
	new Timezone("utc-09", "Coordinated Universal Time-09 (UTC-09:00)", -540, false),
	new Timezone("pacific-standard-time-mexico", "Baja California (UTC-08:00)", -480, true),
	new Timezone("utc-08", "Coordinated Universal Time-08 (UTC-08:00)", -480, false),
	new Timezone("pacific-standard-time", "Pacific Time (US & Canada) (UTC-08:00)", -480, true),
	new Timezone("us-mountain-standard-time", "Arizona (UTC-07:00)", -420, false),
	new Timezone("mountain-standard-time-mexico", "La Paz, Mazatlan (UTC-07:00)", -420, true),
	new Timezone("mountain-standard-time", "Mountain Time (US & Canada) (UTC-07:00)", -420, true),
	new Timezone("yukon-standard-time", "Yukon (UTC-07:00)", -420, true),
	new Timezone("central-america-standard-time", "Central America (UTC-06:00)", -360, false),
	new Timezone("central-standard-time", "Central Time (US & Canada) (UTC-06:00)", -360, true),
	new Timezone("easter-island-standard-time", "Easter Island (UTC-06:00)", -360, true),
	new Timezone("central-standard-time-mexico", "Guadalajara, Mexico City, Monterrey (UTC-06:00)", -360, true),
	new Timezone("canada-central-standard-time", "Saskatchewan (UTC-06:00)", -360, false),
	new Timezone("sa-pacific-standard-time", "Bogota, Lima, Quito, Rio Branco (UTC-05:00)", -300, false),
	new Timezone("eastern-standard-time-mexico", "Chetumal (UTC-05:00)", -300, true),
	new Timezone("eastern-standard-time", "Eastern Time (US & Canada) (UTC-05:00)", -300, true),
	new Timezone("haiti-standard-time", "Haiti (UTC-05:00)", -300, true),
	new Timezone("cuba-standard-time", "Havana (UTC-05:00)", -300, true),
	new Timezone("us-eastern-standard-time", "Indiana (East) (UTC-05:00)", -300, true),
	new Timezone("turks-and-caicos-standard-time", "Turks and Caicos (UTC-05:00)", -300, true),
	new Timezone("paraguay-standard-time", "Asuncion (UTC-04:00)", -240, true),
	new Timezone("atlantic-standard-time", "Atlantic Time (Canada) (UTC-04:00)", -240, true),
	new Timezone("venezuela-standard-time", "Caracas (UTC-04:00)", -240, true),
	new Timezone("central-brazilian-standard-time", "Cuiaba (UTC-04:00)", -240, true),
	new Timezone("sa-western-standard-time", "Georgetown, La Paz, Manaus, San Juan (UTC-04:00)", -240, false),
	new Timezone("pacific-sa-standard-time", "Santiago (UTC-04:00)", -240, true),
	new Timezone("newfoundland-standard-time", "Newfoundland (UTC-03:30)", -210, true),
	new Timezone("tocantins-standard-time", "Araguaina (UTC-03:00)", -180, true),
	new Timezone("e-south-america-standard-time", "Brasilia (UTC-03:00)", -180, true),
	new Timezone("sa-eastern-standard-time", "Cayenne, Fortaleza (UTC-03:00)", -180, false),
	new Timezone("argentina-standard-time", "City of Buenos Aires (UTC-03:00)", -180, true),
	new Timezone("montevideo-standard-time", "Montevideo (UTC-03:00)", -180, true),
	new Timezone("magallanes-standard-time", "Punta Arenas (UTC-03:00)", -180, true),
	new Timezone("saint-pierre-standard-time", "Saint Pierre and Miquelon (UTC-03:00)", -180, true),
	new Timezone("bahia-standard-time", "Salvador (UTC-03:00)", -180, true),
	new Timezone("utc-02", "Coordinated Universal Time-02 (UTC-02:00)", -120, false),
	new Timezone("greenland-standard-time", "Greenland (UTC-02:00)", -120, true),
	new Timezone("mid-atlantic-standard-time", "Mid-Atlantic - Old (UTC-02:00)", -120, true),
	new Timezone("azores-standard-time", "Azores (UTC-01:00)", -60, true),
	new Timezone("cape-verde-standard-time", "Cabo Verde Is. (UTC-01:00)", -60, false),
	new Timezone("utc", "Coordinated Universal Time (UTC)", 0, false),
	new Timezone("gmt-standard-time", "Dublin, Edinburgh, Lisbon, London (UTC+00:00)", 0, true),
	new Timezone("greenwich-standard-time", "Monrovia, Reykjavik (UTC+00:00)", 0, false),
	new Timezone("sao-tome-standard-time", "Sao Tome (UTC+00:00)", 0, true),
	new Timezone("morocco-standard-time", "Casablanca (UTC+01:00)", 0, true),
	new Timezone("w-europe-standard-time", "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna (UTC+01:00)", 60, true),
	new Timezone("central-europe-standard-time", "Belgrade, Bratislava, Budapest, Ljubljana, Prague (UTC+01:00)", 60, true),
	new Timezone("romance-standard-time", "Brussels, Copenhagen, Madrid, Paris (UTC+01:00)", 60, true),
	new Timezone("central-european-standard-time", "Sarajevo, Skopje, Warsaw, Zagreb (UTC+01:00)", 60, true),
	new Timezone("w-central-africa-standard-time", "West Central Africa (UTC+01:00)", 60, false),
	new Timezone("gtb-standard-time", "Athens, Bucharest (UTC+02:00)", 120, true),
	new Timezone("middle-east-standard-time", "Beirut (UTC+02:00)", 120, true),
	new Timezone("egypt-standard-time", "Cairo (UTC+02:00)", 120, true),
	new Timezone("e-europe-standard-time", "Chisinau (UTC+02:00)", 120, true),
	new Timezone("west-bank-standard-time", "Gaza, Hebron (UTC+02:00)", 120, true),
	new Timezone("south-africa-standard-time", "Harare, Pretoria (UTC+02:00)", 120, false),
	new Timezone("fle-standard-time", "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius (UTC+02:00)", 120, true),
	new Timezone("israel-standard-time", "Jerusalem (UTC+02:00)", 120, true),
	new Timezone("south-sudan-standard-time", "Juba (UTC+02:00)", 120, true),
	new Timezone("kaliningrad-standard-time", "Kaliningrad (UTC+02:00)", 120, true),
	new Timezone("sudan-standard-time", "Khartoum (UTC+02:00)", 120, true),
	new Timezone("libya-standard-time", "Tripoli (UTC+02:00)", 120, true),
	new Timezone("namibia-standard-time", "Windhoek (UTC+02:00)", 120, true),
	new Timezone("jordan-standard-time", "Amman (UTC+03:00)", 180, true),
	new Timezone("arabic-standard-time", "Baghdad (UTC+03:00)", 180, true),
	new Timezone("syria-standard-time", "Damascus (UTC+03:00)", 180, true),
	new Timezone("turkey-standard-time", "Istanbul (UTC+03:00)", 180, true),
	new Timezone("arab-standard-time", "Kuwait, Riyadh (UTC+03:00)", 180, false),
	new Timezone("belarus-standard-time", "Minsk (UTC+03:00)", 180, true),
	new Timezone("russian-standard-time", "Moscow, St. Petersburg (UTC+03:00)", 180, true),
	new Timezone("e-africa-standard-time", "Nairobi (UTC+03:00)", 180, false),
	new Timezone("volgograd-standard-time", "Volgograd (UTC+04:00)", 180, true),
	new Timezone("iran-standard-time", "Tehran (UTC+03:30)", 210, true),
	new Timezone("arabian-standard-time", "Abu Dhabi, Muscat (UTC+04:00)", 240, false),
	new Timezone("astrakhan-standard-time", "Astrakhan, Ulyanovsk (UTC+04:00)", 240, true),
	new Timezone("azerbaijan-standard-time", "Baku (UTC+04:00)", 240, true),
	new Timezone("russia-time-zone-3", "Izhevsk, Samara (UTC+04:00)", 240, true),
	new Timezone("mauritius-standard-time", "Port Louis (UTC+04:00)", 240, true),
	new Timezone("saratov-standard-time", "Saratov (UTC+04:00)", 240, true),
	new Timezone("georgian-standard-time", "Tbilisi (UTC+04:00)", 240, false),
	new Timezone("caucasus-standard-time", "Yerevan (UTC+04:00)", 240, true),
	new Timezone("afghanistan-standard-time", "Kabul (UTC+04:30)", 270, false),
	new Timezone("west-asia-standard-time", "Ashgabat, Tashkent (UTC+05:00)", 300, false),
	new Timezone("qyzylorda-standard-time", "Astana (UTC+05:00)", 300, true),
	new Timezone("ekaterinburg-standard-time", "Ekaterinburg (UTC+05:00)", 300, true),
	new Timezone("pakistan-standard-time", "Islamabad, Karachi (UTC+05:00)", 300, true),
	new Timezone("india-standard-time", "Chennai, Kolkata, Mumbai, New Delhi (UTC+05:30)", 330, false),
	new Timezone("sri-lanka-standard-time", "Sri Jayawardenepura (UTC+05:30)", 330, false),
	new Timezone("nepal-standard-time", "Kathmandu (UTC+05:45)", 345, false),
	new Timezone("central-asia-standard-time", "Bishkek (UTC+06:00)", 360, false),
	new Timezone("bangladesh-standard-time", "Dhaka (UTC+06:00)", 360, true),
	new Timezone("omsk-standard-time", "Omsk (UTC+06:00)", 360, true),
	new Timezone("myanmar-standard-time", "Yangon (Rangoon) (UTC+06:30)", 390, false),
	new Timezone("se-asia-standard-time", "Bangkok, Hanoi, Jakarta (UTC+07:00)", 420, false),
	new Timezone("altai-standard-time", "Barnaul, Gorno-Altaysk (UTC+07:00)", 420, true),
	new Timezone("w-mongolia-standard-time", "Hovd (UTC+07:00)", 420, true),
	new Timezone("north-asia-standard-time", "Krasnoyarsk (UTC+07:00)", 420, true),
	new Timezone("n-central-asia-standard-time", "Novosibirsk (UTC+07:00)", 420, true),
	new Timezone("tomsk-standard-time", "Tomsk (UTC+07:00)", 420, true),
	new Timezone("china-standard-time", "Beijing, Chongqing, Hong Kong, Urumqi (UTC+08:00)", 480, false),
	new Timezone("north-asia-east-standard-time", "Irkutsk (UTC+08:00)", 480, true),
	new Timezone("singapore-standard-time", "Kuala Lumpur, Singapore (UTC+08:00)", 480, false),
	new Timezone("w-australia-standard-time", "Perth (UTC+08:00)", 480, true),
	new Timezone("taipei-standard-time", "Taipei (UTC+08:00)", 480, false),
	new Timezone("ulaanbaatar-standard-time", "Ulaanbaatar (UTC+08:00)", 480, true),
	new Timezone("aus-central-w-standard-time", "Eucla (UTC+08:45)", 525, false),
	new Timezone("transbaikal-standard-time", "Chita (UTC+09:00)", 540, true),
	new Timezone("tokyo-standard-time", "Osaka, Sapporo, Tokyo (UTC+09:00)", 540, false),
	new Timezone("north-korea-standard-time", "Pyongyang (UTC+09:00)", 540, true),
	new Timezone("korea-standard-time", "Seoul (UTC+09:00)", 540, false),
	new Timezone("yakutsk-standard-time", "Yakutsk (UTC+09:00)", 540, true),
	new Timezone("cen-australia-standard-time", "Adelaide (UTC+09:30)", 570, true),
	new Timezone("aus-central-standard-time", "Darwin (UTC+09:30)", 570, false),
	new Timezone("e-australia-standard-time", "Brisbane (UTC+10:00)", 600, false),
	new Timezone("aus-eastern-standard-time", "Canberra, Melbourne, Sydney (UTC+10:00)", 600, true),
	new Timezone("west-pacific-standard-time", "Guam, Port Moresby (UTC+10:00)", 600, false),
	new Timezone("tasmania-standard-time", "Hobart (UTC+10:00)", 600, true),
	new Timezone("vladivostok-standard-time", "Vladivostok (UTC+10:00)", 600, true),
	new Timezone("lord-howe-standard-time", "Lord Howe Island (UTC+10:30)", 630, true),
	new Timezone("bougainville-standard-time", "Bougainville Island (UTC+11:00)", 660, true),
	new Timezone("russia-time-zone-10", "Chokurdakh (UTC+11:00)", 660, true),
	new Timezone("magadan-standard-time", "Magadan (UTC+11:00)", 660, true),
	new Timezone("norfolk-standard-time", "Norfolk Island (UTC+11:00)", 660, true),
	new Timezone("sakhalin-standard-time", "Sakhalin (UTC+11:00)", 660, true),
	new Timezone("central-pacific-standard-time", "Solomon Is., New Caledonia (UTC+11:00)", 660, false),
	new Timezone("russia-time-zone-11", "Anadyr, Petropavlovsk-Kamchatsky (UTC+12:00)", 720, true),
	new Timezone("new-zealand-standard-time", "Auckland, Wellington (UTC+12:00)", 720, true),
	new Timezone("utc-12", "Coordinated Universal Time+12 (UTC+12:00)", 720, false),
	new Timezone("fiji-standard-time", "Fiji (UTC+12:00)", 720, true),
	new Timezone("kamchatka-standard-time", "Petropavlovsk-Kamchatsky - Old (UTC+12:00)", 720, true),
	new Timezone("chatham-islands-standard-time", "Chatham Islands (UTC+12:45)", 765, true),
	new Timezone("utc-13", "Coordinated Universal Time+13 (UTC+13:00)", 780, false),
	new Timezone("tonga-standard-time", "Nuku'alofa (UTC+13:00)", 780, true),
	new Timezone("samoa-standard-time", "Samoa (UTC+13:00)", 780, true),
	new Timezone("line-islands-standard-time", "Kiritimati Island (UTC+14:00)", 840, false),
];